import argparse
from pathlib import Path
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
import matplotlib.pyplot as plt

# First-response targets by channel, per support-policy.pdf section 3.
SLA_TARGETS = {
    "chat": pd.Timedelta(minutes=15),
    "voice": pd.Timedelta(hours=2),
    "social": pd.Timedelta(hours=4),
    "email": pd.Timedelta(hours=8),
}
BREACH_CREDIT_INR = 350   # policy section 3
TRANSFER_COST_INR = 305   # policy section 4
N_MONTHS = 18             # Jan 2025 - Jun 2026 inclusive

def load(data_dir):
    p=Path(data_dir)
    t=pd.read_csv(p/"tickets.csv")
    for c in ["created_at","first_response_at","resolved_at"]:
        t[c]=pd.to_datetime(t[c],errors="coerce")
    return t

def data_quality_report(raw, inwin):
    rows=[
        ("Window","Jan 2025-Jun 2026",len(inwin),"Used as stated in brief"),
        ("Rows outside stated window","created_at outside window",len(raw)-len(inwin),"Excluded from analysis"),
        ("Open/pending tickets","status in open,pending",int(inwin.status.isin(["open","pending"]).sum()),"Not treated as attendance"),
        ("Missing transfers","transfers blank",int(inwin.transfers.isna().sum()),"Expected for legacy rows"),
        ("Negative handle time","resolved_at < first_response_at",int((inwin.resolved_at<inwin.first_response_at).sum()),"Not used for labor-cost case"),
        ("Missing CSAT","csat_score blank",int(inwin.csat_score.isna().sum()),"Excluded from CSAT averages"),
    ]
    return pd.DataFrame(rows,columns=["check","definition","count","decision"])

def team_summary_report(t):
    d=t.copy()
    d["target"]=d.channel.map(SLA_TARGETS)
    d["breach"]=(d.first_response_at-d.created_at)>d.target
    total=len(d)
    g=d.groupby("assigned_team")
    rows=[]
    for team,grp in g:
        tickets=len(grp)
        breaches=int(grp.breach.sum())
        rows.append({
            "assigned_team":team,
            "tickets":tickets,
            "avg_monthly":tickets/N_MONTHS,
            "breach_rate":breaches/tickets,
            "breaches":breaches,
            "transfer_count":grp.transfers.sum(skipna=True),
            "csat":grp.csat_score.mean(),
            "ticket_share":tickets/total,
            "breach_credit_inr":breaches*BREACH_CREDIT_INR,
            "transfer_cost_inr":grp.transfers.sum(skipna=True)*TRANSFER_COST_INR,
        })
    return pd.DataFrame(rows).sort_values("tickets",ascending=False).reset_index(drop=True)

def validation_summary_report(t, scores, team_summary, out):
    audit_path=out/"manual_audit_66.csv"
    audit_lines=["## Manual audit"]
    if audit_path.exists():
        audit=pd.read_csv(audit_path)
        correct=int(audit.model_correct.sum())
        n=len(audit)
        audit_lines+= [
            f"- Sample: {n} tickets",
            "- Sampling: 6 per model-predicted category",
            "- Manual review: customer message + agent note",
            f"- Correct: {correct}",
            f"- Error: {n-correct}",
            f"- Agreement: **{correct/n:.1%}**",
            "",
            "### Error pattern",
            "The largest issue is historical `Other`. Several examples are clearly cancellation or delivery cases "
            "even though the original tag remained `Other`. There were also isolated connectivity/billing boundary errors.",
        ]
    else:
        audit_lines.append("`manual_audit_66.csv` not found: this is a human-labeled artifact and is not regenerated by this script.")

    billing=team_summary.set_index("assigned_team").loc["Billing"]
    target_rate=0.10
    fewer_breaches=int(billing.breaches-billing.tickets*target_rate+0.5)  # round half up
    credit_saving=fewer_breaches*BREACH_CREDIT_INR

    lines=["# Validation summary","","## Historical-tag cross-validation",
        "5-fold stratified CV against the historical `category` tag:","",
        f"- Accuracy: **{scores.mean():.1%}**",
        f"- Standard deviation: **{scores.std():.1%}**",
        "- Interpretation: this measures reproducibility against the existing intake tags, not true category correctness.",
        ""] + audit_lines + ["","## Business validation","Billing:",
        f"- {int(billing.tickets):,} tickets",
        f"- {billing.ticket_share:.1%} of the stated window",
        f"- {int(billing.breaches)} first-response breaches",
        f"- {billing.breach_rate:.1%} breach rate",
        f"- {int(billing.breaches)} × Rs {BREACH_CREDIT_INR} = **Rs {int(billing.breach_credit_inr):,}** SLA credits",
        "","Target:",
        f"- {target_rate:.0%} Billing breach rate",
        f"- Approx. {fewer_breaches} fewer breaches over the observed window",
        f"- {fewer_breaches} × Rs {BREACH_CREDIT_INR} = **Rs {credit_saving:,}** potential SLA-credit reduction",
        ""]
    return "\n".join(lines)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--data-dir",default="data")
    ap.add_argument("--output-dir",default="outputs")
    args=ap.parse_args()
    out=Path(args.output_dir); (out/"charts").mkdir(parents=True,exist_ok=True)
    raw=load(args.data_dir)
    t=raw[(raw.created_at>=pd.Timestamp("2025-01-01"))&(raw.created_at<pd.Timestamp("2026-07-01"))].copy()
    data_quality_report(raw,t).to_csv(out/"data_quality.csv",index=False)
    text=(t.customer_message.fillna("")+" \n "+t.agent_notes.fillna("")).str.lower()
    model=Pipeline([
        ("tfidf",TfidfVectorizer(ngram_range=(1,2),min_df=2,max_df=.98,
                                 sublinear_tf=True,max_features=80000)),
        ("clf",LinearSVC(C=1.5,class_weight="balanced"))
    ])
    cv=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
    scores=cross_val_score(model,text,t.category,cv=cv,scoring="accuracy")
    model.fit(text,t.category)
    t["ai_category"]=model.predict(text)
    t["month"]=t.created_at.dt.to_period("M").astype(str)
    t[["ticket_id","created_at","channel","category","ai_category","assigned_team",
       "priority","agent_id","transfers","csat_score","refund_amount_inr",
       "refund_reason_code"]].to_csv(out/"ticket_predictions.csv",index=False)
    t.pivot_table(index="month",columns="ai_category",values="ticket_id",
                  aggfunc="count",fill_value=0).to_csv(out/"monthly_category.csv")
    t.pivot_table(index="month",columns="assigned_team",values="ticket_id",
                  aggfunc="count",fill_value=0).to_csv(out/"monthly_team.csv")
    team_summary=team_summary_report(t)
    team_summary.to_csv(out/"team_summary.csv",index=False)
    (out/"validation_summary.md").write_text(
        validation_summary_report(t,scores,team_summary,out),encoding="utf-8")
    for col,title,file in [
        ("ai_category","Vireo Audio — Monthly Ticket Volume by AI Category","monthly_category.png"),
        ("assigned_team","Vireo Audio — Monthly Ticket Volume by Assigned Team","monthly_team.png")]:
        d=t.pivot_table(index="month",columns=col,values="ticket_id",aggfunc="count",fill_value=0)
        ax=d.plot(figsize=(12,6))
        ax.set_xlabel("Month"); ax.set_ylabel("Tickets"); ax.set_title(title)
        plt.tight_layout(); plt.savefig(out/"charts"/file,dpi=160); plt.close()
    print(f"Tickets in stated window: {len(t):,}")
    print(f"5-fold CV accuracy vs historical tags: {scores.mean():.1%} (sd {scores.std():.1%})")
    print(f"Outputs written to {out.resolve()}")

if __name__=="__main__":
    main()
